version: '3.9'

services:
  api:
    container_name: api
    # Dockerfileの場所
    build: ./echo
    volumes:
      - type: bind
        source: ./echo
        target: /app
    ports:
      - 5050:5050

volumes:
  api-data: